const ATTACHED = ["attached-recipe", "health-conscious-adaptation", "estimated-calories"];
const EYE = ["eye-supportive", "vitamin-a-foods", "lutein-zeaxanthin-foods", "estimated-calories"];

const recipe = (name, cat, cal, time, tags, imageKey, ingredients, steps, source, sourceNote, aliases = []) => ({
  name, cat, cal, time, tags, imageKey, ingredients, steps, source, sourceNote, aliases
});

const cookbookSource = "Cook Book.docx.pdf / Flavorful Healthy Diet_ A Cookbook.pptx.pdf";
const cookbookNote = "Adapted from the attached cookbook with practical portions and lighter ingredient choices for NourishPlan.";
const menuSource = "Menu.pdf";
const menuNote = "The attached menu supplied the dish name; NourishPlan added a balanced home-cooking method and estimated nutrition.";

export const EYE_SUPPORTIVE_RECIPES = [
  recipe("Carrot-Ginger Red Lentil Soup", "lunch", 330, 35, [...EYE, "high-fiber", "plant-protein", "no-added-sugar"], "soup",
    [[1, "cup", "carrot"], [0.5, "cup", "red lentils"], [0.25, "cup", "onion"], [2, "clove", "garlic"], [1, "tsp", "fresh ginger"], [2, "cup", "unsalted vegetable broth"], [1, "tsp", "olive oil"], [0.25, "tsp", "turmeric"], [1, "tbsp", "calamansi juice"]],
    ["Heat the olive oil and soften the onion, garlic and ginger for three minutes.", "Add the carrots, lentils, turmeric and broth; simmer for 24 to 28 minutes until tender.", "Blend until mostly smooth, leaving a little texture.", "Finish with calamansi juice and black pepper; do not add sugar."],
    "NourishPlan eye-supportive collection", "Built around carrots and other vitamin-A-containing foods; it supports a balanced diet and is not a treatment for an eye condition."),
  recipe("Roasted Carrot & Chickpea Quinoa Bowl", "lunch", 430, 35, [...EYE, "high-fiber", "plant-protein", "whole-grain"], "salad",
    [[1.5, "cup", "carrot"], [0.75, "cup", "cooked chickpeas"], [0.5, "cup", "cooked quinoa"], [1, "cup", "baby spinach"], [2, "tsp", "olive oil"], [1, "tbsp", "lemon juice"], [1, "tbsp", "pumpkin seeds"], [0.5, "tsp", "ground cumin"]],
    ["Heat the oven to 210°C.", "Toss carrots and chickpeas with half the oil and cumin; roast for 22 to 25 minutes.", "Layer quinoa and spinach in a bowl, then add the warm roasted vegetables.", "Dress with the remaining olive oil and lemon juice and finish with pumpkin seeds."],
    "NourishPlan eye-supportive collection", "Pairs orange vegetables with leafy greens and a small amount of unsaturated fat."),
  recipe("Carrot Oat Breakfast Muffins", "breakfast", 280, 35, [...EYE, "whole-grain", "no-refined-sugar", "portion-aware"], "pancakes",
    [[0.75, "cup", "rolled oats"], [0.75, "cup", "grated carrot"], [1, "", "egg"], [0.5, "pc", "ripe banana"], [0.25, "cup", "low-fat milk"], [1, "tbsp", "ground flaxseed"], [0.5, "tsp", "baking powder"], [0.5, "tsp", "cinnamon"], [1, "tsp", "olive oil"]],
    ["Heat the oven to 180°C and lightly oil four muffin cups.", "Blend the oats into flour, then stir in flaxseed, baking powder and cinnamon.", "Mash the banana and whisk with the egg and milk; fold in the grated carrot and dry mixture.", "Divide among the cups and bake for 20 to 23 minutes; cool for five minutes before serving."],
    "NourishPlan eye-supportive collection", "Uses carrots plus whole oats and has no refined sugar."),
  recipe("Salmon, Squash & Pechay Plate", "dinner", 520, 35, [...EYE, "omega-3", "leafy-greens", "high-protein", "lower-sodium"], "salmonSweetPotato",
    [[140, "g", "salmon fillet"], [1, "cup", "squash"], [1.5, "cup", "pechay"], [0.5, "cup", "cooked brown rice"], [2, "tsp", "olive oil"], [1, "tbsp", "calamansi juice"], [1, "clove", "garlic"], [0.25, "tsp", "black pepper"]],
    ["Heat the oven to 200°C and place the squash on a lined tray with half the olive oil.", "Roast for 12 minutes, add the salmon, and cook for another 12 to 14 minutes until the center reaches 63°C.", "Sauté the garlic and pechay in the remaining oil until just wilted.", "Serve with brown rice and calamansi juice."],
    "NourishPlan eye-supportive collection", "Combines leafy greens, orange squash and salmon in one balanced plate."),
];

export const COOKBOOK_RECIPES = [
  recipe("Lemon Chamomile Tea", "snack", 10, 12, [...ATTACHED, "caffeine-free", "no-added-sugar"], "tea",
    [[1, "tsp", "dried chamomile flowers"], [1, "tsp", "dried peppermint leaves"], [1, "tsp", "fennel seeds"], [0.5, "tsp", "dried ginger"], [1, "cup", "boiling water"], [1, "slice", "lemon"]],
    ["Combine chamomile, peppermint, fennel and ginger in a mug.", "Pour over boiling water, cover and steep for 10 minutes.", "Strain, add lemon and serve hot or chilled without sweetener."], cookbookSource, cookbookNote),
  recipe("Chicken Oyakodon", "lunch", 470, 35, [...ATTACHED, "high-protein", "lower-sodium"], "chickenRice",
    [[0.5, "cup", "cooked brown rice"], [120, "g", "skinless chicken thigh"], [0.5, "cup", "onion"], [0.75, "cup", "low-sodium dashi stock"], [1, "tbsp", "low-sodium soy sauce"], [1, "tsp", "mirin"], [1, "", "egg"], [1, "cup", "pechay"]],
    ["Warm the chicken and onion in a covered skillet until the chicken begins to brown.", "Add dashi, soy sauce and mirin; simmer until the chicken reaches 74°C.", "Pour in the beaten egg, cover and steam until set.", "Serve over brown rice with wilted pechay."], cookbookSource, cookbookNote),
  recipe("Caesar Salad", "lunch", 330, 20, [...ATTACHED, "leafy-greens", "portion-aware"], "salad",
    [[3, "cup", "romaine lettuce"], [0.33, "cup", "whole-grain croutons"], [0.25, "cup", "plain Greek yogurt"], [1, "pc", "anchovy fillet"], [1, "tbsp", "grated parmesan"], [1, "tsp", "Dijon mustard"], [1, "tbsp", "lemon juice"], [1, "clove", "garlic"], [0.25, "tsp", "black pepper"]],
    ["Mash the anchovy and garlic, then whisk with yogurt, mustard, lemon and pepper.", "Toss the romaine with the dressing.", "Add whole-grain croutons and a measured tablespoon of parmesan."], cookbookSource, cookbookNote),
  recipe("Seafood Linguine", "dinner", 510, 35, [...ATTACHED, "high-protein", "tomato-rich"], "pasta",
    [[70, "g", "whole-wheat linguine"], [80, "g", "shrimp"], [60, "g", "squid"], [6, "pc", "mussels"], [1, "cup", "cherry tomatoes"], [1, "tbsp", "tomato paste"], [2, "tsp", "olive oil"], [2, "clove", "garlic"], [0.25, "tsp", "chili flakes"], [2, "tbsp", "fresh parsley"]],
    ["Cook linguine until al dente and reserve a little pasta water.", "Sauté garlic in olive oil, add tomato paste and tomatoes, then loosen with pasta water.", "Add shrimp, squid and mussels; cover until the mussels open and discard any that stay closed.", "Toss with linguine and parsley and serve immediately."], cookbookSource, cookbookNote),
  recipe("Halo-Halo", "snack", 290, 15, [...ATTACHED, "Filipino", "occasional-treat", "portion-aware"], "coconut",
    [[0.25, "cup", "ripe banana"], [0.25, "cup", "jackfruit"], [0.25, "cup", "cooked white beans"], [0.25, "cup", "nata de coco"], [1, "cup", "crushed ice"], [0.33, "cup", "low-fat evaporated milk"], [2, "tbsp", "ube yogurt"], [1, "tbsp", "pandan jelly"]],
    ["Chill the fruit, beans and milk.", "Layer banana, jackfruit, white beans, nata de coco and pandan jelly in a glass.", "Add crushed ice and evaporated milk, then finish with a small spoonful of ube yogurt."], cookbookSource, cookbookNote),
  recipe("Chicken Quesadilla", "lunch", 460, 30, [...ATTACHED, "high-protein", "whole-grain", "vegetable-rich"], "wrap",
    [[120, "g", "skinless chicken breast"], [1, "pc", "whole-wheat tortilla"], [0.5, "cup", "red bell pepper"], [0.5, "cup", "green bell pepper"], [0.25, "cup", "onion"], [0.25, "cup", "reduced-fat cheddar"], [1, "tsp", "olive oil"], [0.5, "tsp", "ground cumin"], [0.5, "tsp", "paprika"]],
    ["Season the chicken with cumin and paprika and cook until it reaches 74°C.", "Sauté the peppers and onion in olive oil.", "Fill the tortilla with chicken, vegetables and measured cheese, fold, and toast on both sides until crisp."], cookbookSource, cookbookNote),
  recipe("Napoleones Cream Puff", "snack", 260, 70, [...ATTACHED, "occasional-treat", "portion-aware"], "cake",
    [[35, "g", "puff pastry"], [0.25, "cup", "low-fat milk"], [1, "", "egg yolk"], [1, "tbsp", "cornstarch"], [1, "tsp", "butter"], [2, "tsp", "sugar"], [0.25, "tsp", "vanilla extract"]],
    ["Bake a small puff-pastry rectangle at 200°C until golden and cool completely.", "Whisk milk, egg yolk, cornstarch, sugar and vanilla over low heat until thick; cool.", "Split the pastry and add a thin layer of custard.", "Serve one small piece as an occasional dessert."], cookbookSource, cookbookNote),
  recipe("Chicken Teriyaki", "dinner", 450, 35, [...ATTACHED, "high-protein", "lower-sodium", "no-refined-sugar"], "chickenVegetables",
    [[150, "g", "skinless chicken thigh"], [1, "tbsp", "low-sodium soy sauce"], [2, "tbsp", "pineapple juice"], [1, "tsp", "rice vinegar"], [1, "tsp", "fresh ginger"], [2, "clove", "garlic"], [1, "tsp", "cornstarch"], [1, "cup", "broccoli"], [0.5, "cup", "cooked brown rice"]],
    ["Whisk soy sauce, pineapple juice, vinegar, ginger, garlic and cornstarch.", "Cook the chicken in a nonstick pan until nearly done, then add the sauce and simmer until it reaches 74°C.", "Steam the broccoli and serve with the chicken and measured brown rice."], cookbookSource, cookbookNote),
  recipe("Chocolate Chip Ice Cream", "snack", 230, 10, [...ATTACHED, "occasional-treat", "portion-aware"], "dessert",
    [[0.5, "cup", "plain Greek yogurt"], [0.5, "pc", "ripe banana"], [1, "tbsp", "mini dark chocolate chips"], [0.25, "tsp", "vanilla extract"], [0.125, "tsp", "peppermint extract"]],
    ["Blend the yogurt, frozen banana, vanilla and peppermint until smooth.", "Fold in the dark chocolate chips.", "Freeze for 60 to 90 minutes and serve a half-cup portion."], cookbookSource, cookbookNote),
  recipe("Garden Salad", "lunch", 260, 15, [...ATTACHED, ...EYE, "vegetable-rich"], "salad",
    [[2, "cup", "romaine lettuce"], [0.5, "cup", "endive"], [0.5, "cup", "grape tomatoes"], [0.5, "cup", "carrot"], [0.5, "cup", "cucumber"], [0.25, "cup", "radish"], [0.125, "cup", "red onion"], [1, "tbsp", "black olives"], [1, "tbsp", "light honey mustard dressing"]],
    ["Wash and dry all vegetables.", "Combine the greens, tomatoes, carrot, cucumber, radish, onion and olives.", "Toss with a measured tablespoon of dressing just before serving."], cookbookSource, cookbookNote),
  recipe("Mango Cheesecake", "snack", 270, 25, [...ATTACHED, "occasional-treat", "portion-aware"], "cake",
    [[0.33, "cup", "plain Greek yogurt"], [2, "tbsp", "light cream cheese"], [0.33, "cup", "fresh mango"], [2, "tbsp", "crushed graham crackers"], [1, "tsp", "melted butter"], [0.5, "tsp", "unflavored gelatin"], [1, "tsp", "honey"]],
    ["Mix the graham crumbs and butter and press into a small ramekin.", "Blend yogurt, cream cheese, honey and half the mango.", "Dissolve gelatin as directed, mix it into the filling, and spoon over the crust.", "Top with remaining mango and chill until set."], cookbookSource, cookbookNote),
  recipe("Watermelon Bingsu", "snack", 180, 10, [...ATTACHED, "refreshing", "portion-aware"], "fruit",
    [[1.5, "cup", "shaved ice"], [1.5, "cup", "watermelon"], [2, "tbsp", "low-fat milk"], [0.25, "cup", "blueberries"], [1, "tsp", "chia seeds"]],
    ["Shave or finely crush the ice into a chilled bowl.", "Cover with watermelon and blueberries.", "Drizzle with low-fat milk, sprinkle with chia seeds and serve immediately."], cookbookSource, cookbookNote),
];

export const MENU_RECIPES = [
  recipe("Salmon & Spinach with Tartar Cream", "dinner", 510, 30, [...ATTACHED, ...EYE, "omega-3", "leafy-greens"], "salmon", [[140, "g", "salmon fillet"], [2, "cup", "spinach"], [2, "tbsp", "plain Greek yogurt"], [1, "tsp", "capers"], [1, "tbsp", "lemon juice"], [1, "tsp", "olive oil"]], ["Bake the salmon at 200°C until it reaches 63°C.", "Wilt the spinach in olive oil.", "Mix yogurt, capers and lemon for the tartar cream and spoon over the fish."], menuSource, menuNote),
  recipe("Superhealthy Salmon Burgers", "lunch", 470, 30, [...ATTACHED, "omega-3", "high-protein", "whole-grain"], "salmon", [[140, "g", "salmon fillet"], [0.25, "cup", "rolled oats"], [1, "tbsp", "green onion"], [1, "tbsp", "lemon juice"], [1, "pc", "whole-grain bun"], [1, "cup", "lettuce"], [0.5, "cup", "tomato"]], ["Pulse salmon with oats, green onion and lemon and form a patty.", "Cook in a nonstick pan until the center reaches 63°C.", "Serve in the whole-grain bun with lettuce and tomato."], menuSource, menuNote),
  recipe("Salmon Egg-Fried Rice", "lunch", 490, 25, [...ATTACHED, "high-protein", "whole-grain"], "chickenRice", [[100, "g", "salmon fillet"], [0.75, "cup", "cooked brown rice"], [1, "", "egg"], [0.5, "cup", "carrot"], [0.5, "cup", "green peas"], [1, "tsp", "sesame oil"], [1, "tsp", "low-sodium soy sauce"]], ["Flake cooked salmon into large pieces.", "Stir-fry carrot and peas in sesame oil, then add rice.", "Push aside, scramble the egg, fold in salmon and finish with low-sodium soy sauce."], menuSource, menuNote),
  recipe("Cilantro-Lime Tilapia with Spinach & Tomatoes", "dinner", 390, 25, [...ATTACHED, ...EYE, "lean-protein", "leafy-greens"], "fishSalad", [[150, "g", "tilapia fillet"], [2, "cup", "spinach"], [1, "cup", "tomato"], [2, "tbsp", "cilantro"], [1, "tbsp", "lime juice"], [2, "tsp", "olive oil"]], ["Season tilapia with pepper and lime.", "Pan-cook in half the oil until opaque and the center reaches 63°C.", "Wilt spinach and tomatoes in the remaining oil and finish with cilantro."], menuSource, menuNote),
  recipe("Chicken, Red Pepper & Almond Traybake", "dinner", 480, 40, [...ATTACHED, "high-protein", "vegetable-rich"], "roastChickenSweetPotato", [[150, "g", "skinless chicken breast"], [1, "cup", "red bell pepper"], [0.5, "cup", "red onion"], [1, "cup", "sweet potato"], [1, "tbsp", "almonds"], [2, "tsp", "olive oil"], [0.5, "tsp", "paprika"]], ["Heat the oven to 210°C.", "Toss chicken, pepper, onion and sweet potato with oil and paprika.", "Roast for 25 to 30 minutes until chicken reaches 74°C; add almonds for the final five minutes."], menuSource, menuNote),
  recipe("Honey-Soy Chicken with Sesame Broccoli", "dinner", 470, 30, [...ATTACHED, "high-protein", "lower-sodium"], "chickenVegetables", [[150, "g", "skinless chicken breast"], [1.5, "cup", "broccoli"], [1, "tbsp", "low-sodium soy sauce"], [1, "tsp", "honey"], [1, "tsp", "sesame oil"], [1, "tsp", "sesame seeds"], [1, "tsp", "fresh ginger"]], ["Whisk soy sauce, honey, sesame oil and ginger.", "Cook the chicken until browned, add the sauce and simmer until it reaches 74°C.", "Steam broccoli and serve with the chicken and sesame seeds."], menuSource, menuNote),
  recipe("Lemon-Yogurt Chicken Flatbreads", "lunch", 460, 30, [...ATTACHED, "high-protein", "whole-grain"], "wrap", [[130, "g", "skinless chicken breast"], [1, "pc", "whole-wheat flatbread"], [0.25, "cup", "plain Greek yogurt"], [1, "tbsp", "lemon juice"], [1, "cup", "lettuce"], [0.5, "cup", "cucumber"], [0.5, "cup", "tomato"]], ["Marinate chicken with half the yogurt and lemon for 15 minutes.", "Cook until the center reaches 74°C and slice.", "Fill the flatbread with lettuce, cucumber, tomato, chicken and remaining yogurt."], menuSource, menuNote),
  recipe("Lemon Chicken Piccata", "dinner", 430, 30, [...ATTACHED, "high-protein", "lower-sodium"], "chickenVegetables", [[150, "g", "skinless chicken breast"], [1, "tbsp", "whole-wheat flour"], [1, "tbsp", "lemon juice"], [1, "tsp", "capers"], [0.5, "cup", "unsalted chicken broth"], [2, "tsp", "olive oil"], [1, "cup", "green beans"]], ["Lightly coat the chicken in flour and brown it in olive oil.", "Add broth, lemon and capers and simmer until chicken reaches 74°C.", "Serve with steamed green beans."], menuSource, menuNote),
  recipe("Chocolate & Berry Mousse Pots", "snack", 220, 15, [...ATTACHED, "portion-aware", "occasional-treat"], "dessert", [[0.5, "cup", "plain Greek yogurt"], [1, "tbsp", "unsweetened cocoa powder"], [0.5, "cup", "mixed berries"], [1, "tsp", "honey"], [1, "tbsp", "chia seeds"]], ["Whisk yogurt, cocoa and honey until smooth.", "Fold in half the berries and chia seeds.", "Divide into small pots, chill for 20 minutes and top with remaining berries."], menuSource, menuNote),
  recipe("Chocolate Muffins with Hot Chocolate Mustard", "snack", 250, 35, [...ATTACHED, "portion-aware", "occasional-treat"], "cake", [[0.5, "cup", "whole-wheat flour"], [0.25, "cup", "rolled oats"], [2, "tbsp", "unsweetened cocoa powder"], [0.5, "pc", "ripe banana"], [1, "", "egg"], [0.25, "cup", "low-fat milk"], [0.5, "tsp", "baking powder"], [0.25, "tsp", "mustard powder"]], ["Heat the oven to 180°C and line four muffin cups.", "Combine the dry ingredients, including only a small pinch of mustard powder.", "Whisk banana, egg and milk, fold into the dry mix, and bake for 18 to 20 minutes."], menuSource, "The unusual name is preserved exactly from Menu.pdf; this version uses a very small amount of mustard powder with cocoa."),
  recipe("Chocolate & Raspberry Birthday Layer Cake", "snack", 290, 55, [...ATTACHED, "portion-aware", "occasional-treat"], "cake", [[0.5, "cup", "whole-wheat flour"], [2, "tbsp", "unsweetened cocoa powder"], [1, "", "egg"], [0.33, "cup", "low-fat milk"], [0.5, "pc", "ripe banana"], [0.5, "cup", "raspberries"], [0.33, "cup", "plain Greek yogurt"], [1, "tsp", "honey"]], ["Bake two small cocoa-banana cake layers at 180°C until a tester comes out clean.", "Cool completely.", "Layer with Greek yogurt and raspberries, then chill before slicing into small portions."], menuSource, menuNote),
  recipe("Healthy Chocolate Ice Cream", "snack", 200, 10, [...ATTACHED, "no-refined-sugar", "portion-aware"], "dessert", [[1, "pc", "frozen banana"], [0.33, "cup", "plain Greek yogurt"], [1, "tbsp", "unsweetened cocoa powder"], [1, "tbsp", "peanut butter"], [0.25, "tsp", "vanilla extract"]], ["Blend frozen banana, yogurt, cocoa, peanut butter and vanilla until smooth.", "Freeze for 30 minutes for a firmer texture.", "Serve a measured half-cup portion."], menuSource, menuNote),
  recipe("Lemon Spaghetti with Tuna & Broccoli", "lunch", 480, 25, [...ATTACHED, "whole-grain", "high-protein"], "pasta", [[70, "g", "whole-wheat spaghetti"], [1, "can", "tuna in water"], [1.5, "cup", "broccoli"], [1, "tbsp", "lemon juice"], [1, "tsp", "lemon zest"], [2, "tsp", "olive oil"], [1, "clove", "garlic"]], ["Cook spaghetti and broccoli together until al dente and reserve pasta water.", "Sauté garlic in olive oil and add drained tuna.", "Toss with pasta, broccoli, lemon juice, zest and enough pasta water to coat."], menuSource, menuNote),
  recipe("Sausage Ragu", "dinner", 500, 40, [...ATTACHED, "vegetable-rich", "portion-aware"], "pasta", [[100, "g", "lean chicken sausage"], [1, "cup", "crushed tomatoes"], [0.5, "cup", "carrot"], [0.5, "cup", "mushrooms"], [0.25, "cup", "onion"], [1, "clove", "garlic"], [60, "g", "whole-wheat pasta"], [1, "tsp", "olive oil"]], ["Brown the chicken sausage and break it into small pieces.", "Add onion, garlic, carrot, mushrooms and tomatoes and simmer for 25 minutes.", "Serve over cooked whole-wheat pasta."], menuSource, menuNote),
  recipe("Spaghetti Puttanesca", "dinner", 440, 25, [...ATTACHED, "tomato-rich", "whole-grain"], "pasta", [[70, "g", "whole-wheat spaghetti"], [1, "cup", "crushed tomatoes"], [1, "tbsp", "black olives"], [1, "tsp", "capers"], [1, "pc", "anchovy fillet"], [1, "clove", "garlic"], [1, "tsp", "olive oil"], [0.25, "tsp", "chili flakes"]], ["Cook spaghetti until al dente.", "Sauté garlic and anchovy in olive oil, then add tomatoes, olives, capers and chili.", "Simmer for 12 minutes and toss with the pasta."], menuSource, menuNote),
  recipe("Child-Friendly Thai Chicken Noodles", "lunch", 460, 30, [...ATTACHED, "high-protein", "vegetable-rich", "mild"], "pancit", [[120, "g", "skinless chicken breast"], [60, "g", "rice noodles"], [0.5, "cup", "carrot"], [0.5, "cup", "bell pepper"], [0.5, "cup", "snap peas"], [1, "tbsp", "lime juice"], [1, "tsp", "low-sodium soy sauce"], [1, "tsp", "sesame oil"]], ["Soak noodles according to the package.", "Cook chicken in sesame oil until it reaches 74°C, then add vegetables.", "Toss with noodles, lime and low-sodium soy sauce; keep the dish mild."], menuSource, menuNote),
  recipe("Puttanesca Baked Gnocchi", "dinner", 500, 35, [...ATTACHED, "tomato-rich", "portion-aware"], "pasta", [[1, "cup", "whole-wheat gnocchi"], [1, "cup", "crushed tomatoes"], [1, "tbsp", "black olives"], [1, "tsp", "capers"], [1, "cup", "spinach"], [2, "tbsp", "part-skim mozzarella"], [1, "clove", "garlic"]], ["Combine gnocchi, tomatoes, olives, capers, garlic and spinach in a small baking dish.", "Cover and bake at 200°C for 20 minutes.", "Top with mozzarella and bake uncovered until bubbling."], menuSource, menuNote),
  recipe("Lemony Tuna, Tomato & Caper One-Pot Pasta", "lunch", 470, 25, [...ATTACHED, "high-protein", "whole-grain"], "pasta", [[70, "g", "whole-wheat pasta"], [1, "can", "tuna in water"], [1, "cup", "cherry tomatoes"], [1, "tsp", "capers"], [1, "tbsp", "lemon juice"], [1, "tsp", "olive oil"], [1, "clove", "garlic"]], ["Simmer pasta, tomatoes and garlic with just enough water to cook the pasta.", "Fold in drained tuna and capers.", "Finish with lemon juice and olive oil."], menuSource, menuNote),
  recipe("Mushroom & Thyme Risotto", "dinner", 430, 35, [...ATTACHED, "vegetarian", "portion-aware"], "rice", [[0.5, "cup", "arborio rice"], [1.5, "cup", "mushrooms"], [2, "cup", "unsalted vegetable broth"], [0.25, "cup", "onion"], [1, "clove", "garlic"], [1, "tsp", "olive oil"], [1, "tsp", "fresh thyme"], [1, "tbsp", "grated parmesan"]], ["Sauté onion, garlic and mushrooms in olive oil.", "Add rice and stir, then add warm broth gradually until creamy and al dente.", "Finish with thyme and a measured tablespoon of parmesan."], menuSource, menuNote),
  recipe("Agua Fresca de Pepino", "snack", 45, 10, [...ATTACHED, "refreshing", "no-added-sugar"], "drink", [[1, "cup", "cucumber"], [1, "tbsp", "lime juice"], [1, "cup", "cold water"], [0.5, "cup", "ice"], [4, "leaf", "mint"]], ["Blend cucumber, lime, water and mint.", "Strain if preferred.", "Serve over ice without added sugar."], menuSource, menuNote),
  recipe("Mexican-Inspired Fruit Salad", "snack", 160, 12, [...ATTACHED, "fruit-rich", "no-added-sugar"], "fruit", [[0.5, "cup", "mango"], [0.5, "cup", "watermelon"], [0.5, "cup", "pineapple"], [0.5, "cup", "cucumber"], [1, "tbsp", "lime juice"], [0.125, "tsp", "chili powder"]], ["Cube the fruit and cucumber.", "Toss with lime juice and a small pinch of chili.", "Chill briefly and serve."], menuSource, menuNote),
  recipe("Strawberry-Melon Summer Salad", "snack", 150, 10, [...ATTACHED, "fruit-rich", "no-added-sugar"], "fruit", [[1, "cup", "strawberries"], [1, "cup", "melon"], [1, "tbsp", "lime juice"], [1, "tbsp", "fresh mint"], [1, "tbsp", "pumpkin seeds"]], ["Slice the strawberries and melon.", "Toss with lime juice and mint.", "Finish with pumpkin seeds and serve chilled."], menuSource, menuNote),
];

const pantrySource = "Here are four distinct recipes you can make using only the ingredients you listed-.pdf";
const pantryNote = "Imported from the attached pantry-recipe PDF and standardized into measurable portions.";
export const PANTRY_RECIPES = [
  recipe("Calamansi-Garlic Shrimp Pasta", "dinner", 470, 25, [...ATTACHED, "high-protein"], "pasta", [[70, "g", "whole-wheat pasta"], [120, "g", "shrimp"], [2, "tbsp", "calamansi juice"], [2, "clove", "garlic"], [0.25, "cup", "onion"], [2, "tsp", "olive oil"], [1, "tbsp", "grated parmesan"], [0.5, "tsp", "dried oregano"]], ["Cook pasta until al dente and reserve pasta water.", "Sauté garlic, onion and shrimp until the shrimp are opaque.", "Add calamansi and pasta water, toss with the pasta, oregano and parmesan."], pantrySource, pantryNote),
  recipe("Savory Sardine & Tomato Noodle Stir-Fry", "lunch", 430, 20, [...ATTACHED, "omega-3", "budget-friendly"], "pancit", [[60, "g", "whole-grain noodles"], [1, "can", "sardines in tomato sauce"], [1, "cup", "tomato"], [0.25, "cup", "onion"], [1, "clove", "garlic"], [1, "pack", "seaweed crisps"]], ["Prepare noodles according to the package.", "Sauté onion, garlic and tomato, then add sardines and break them into chunks.", "Toss in the noodles and finish with crushed seaweed crisps."], pantrySource, pantryNote),
  recipe("Dark Chocolate & Orange Pancakes", "breakfast", 330, 20, [...ATTACHED, "whole-grain", "portion-aware"], "pancakes", [[0.5, "cup", "oat pancake mix"], [0.33, "cup", "unsweetened oat milk"], [0.5, "pc", "orange"], [1, "tbsp", "dark chocolate"], [0.25, "tsp", "cinnamon"]], ["Prepare the pancake batter with oat milk, cinnamon, orange zest and chopped dark chocolate.", "Cook small pancakes in a nonstick pan.", "Serve with orange segments instead of syrup."], pantrySource, pantryNote),
  recipe("Creamy Tuna & Cheese Salad Wrap", "lunch", 410, 12, [...ATTACHED, "high-protein", "whole-grain"], "wrap", [[1, "can", "tuna in water"], [2, "tbsp", "plain Greek yogurt"], [1, "tsp", "light mayonnaise"], [1, "tbsp", "lemon juice"], [2, "tbsp", "onion"], [1, "tbsp", "walnuts"], [1, "pc", "whole-wheat tortilla"], [1, "cup", "lettuce"]], ["Drain the tuna.", "Mix with yogurt, mayonnaise, lemon, onion and crushed walnuts.", "Wrap with lettuce in the whole-wheat tortilla."], pantrySource, pantryNote),
  recipe("Malunggay-Okra-Luya Morning Wellness Drink", "snack", 70, 5, [...ATTACHED, "no-added-sugar", "vegetable-based"], "drink", [[2, "tbsp", "malunggay okra luya concentrate"], [0.5, "cup", "orange juice"], [1, "tbsp", "calamansi juice"], [0.5, "cup", "cold water"]], ["Combine the concentrate, orange juice, calamansi and cold water.", "Stir well and serve chilled.", "Use unsweetened concentrate and do not exceed its package serving."], pantrySource, pantryNote),
];

const spreadSource = "Healthy Sandwich Spread Recipes - Sheet1.pdf";
const spreadNote = "Imported from the attached sandwich-spread sheet; close variants are consolidated as aliases to prevent duplicates.";
export const SPREAD_RECIPES = [
  recipe("Savory Sardine & Lemon Spread", "snack", 190, 8, [...ATTACHED, "high-protein", "omega-3"], "fish", [[1, "can", "sardines"], [1, "tbsp", "light mayonnaise"], [1, "tsp", "calamansi juice"], [1, "tbsp", "red onion"], [0.25, "tsp", "black pepper"]], ["Drain and mash the sardines.", "Mix with mayonnaise, calamansi, onion and pepper.", "Chill and serve two tablespoons on whole-grain bread or cucumber."], spreadSource, spreadNote),
  recipe("Creamy Egg & Mustard Salad Spread", "snack", 170, 10, [...ATTACHED, "high-protein", "quick"], "eggs", [[2, "", "hard-boiled egg"], [1, "tbsp", "plain Greek yogurt"], [1, "tsp", "mustard"], [0.25, "tsp", "black pepper"]], ["Chop the eggs.", "Mix with yogurt, mustard and pepper.", "Chill before spreading."], spreadSource, spreadNote, ["Egg Mayo Lite (Convenience Version)"]),
  recipe("Tuna & Corn Relish Spread", "snack", 190, 8, [...ATTACHED, "high-protein", "quick"], "fish", [[1, "can", "tuna in water"], [2, "tbsp", "whole-kernel corn"], [1, "tbsp", "plain Greek yogurt"], [0.25, "tsp", "black pepper"]], ["Drain the tuna and corn.", "Mix with yogurt and pepper.", "Chill and serve in a measured portion."], spreadSource, spreadNote),
  recipe("Creamy Tuna & Mayo Spread", "snack", 180, 8, [...ATTACHED, "high-protein", "quick"], "fish", [[1, "can", "tuna in water"], [1, "tbsp", "light mayonnaise"], [1, "tsp", "calamansi juice"], [0.5, "tsp", "onion powder"], [0.25, "tsp", "black pepper"]], ["Drain and flake the tuna.", "Mix with mayonnaise, calamansi, onion powder and pepper.", "Refrigerate until serving."], spreadSource, spreadNote),
  recipe("Filipino-Style Egg Spread", "snack", 180, 10, [...ATTACHED, "high-protein", "quick"], "eggs", [[2, "", "hard-boiled egg"], [1, "tbsp", "light mayonnaise"], [0.5, "tsp", "garlic powder"], [0.25, "tsp", "black pepper"]], ["Chop the eggs finely.", "Fold in mayonnaise, garlic powder and pepper.", "Chill and serve on whole-grain bread."], spreadSource, spreadNote),
  recipe("Savory Peanut Butter Spread", "snack", 210, 5, [...ATTACHED, "plant-protein", "quick"], "apple", [[3, "tbsp", "unsweetened peanut butter"], [1, "tsp", "low-sodium soy sauce"], [1, "tsp", "calamansi juice"], [0.5, "tsp", "garlic powder"], [1, "tbsp", "warm water"], [0.125, "tsp", "chili flakes"]], ["Whisk peanut butter, soy sauce, calamansi and garlic.", "Add warm water until spreadable.", "Finish with optional chili flakes."], spreadSource, spreadNote),
  recipe("Tuna Calamansi Yogurt Spread", "snack", 170, 8, [...ATTACHED, "high-protein", "quick"], "fish", [[1, "can", "tuna in water"], [2, "tbsp", "plain yogurt"], [1, "tsp", "calamansi juice"], [0.25, "tsp", "black pepper"], [0.25, "cup", "cucumber"]], ["Drain the tuna.", "Mix with yogurt, calamansi and pepper.", "Fold in finely chopped cucumber and chill."], spreadSource, spreadNote, ["Tuna Yogurt Spread"]),
  recipe("Peanut Butter Banana Spread", "snack", 220, 5, [...ATTACHED, "plant-protein", "quick"], "apple", [[2, "tbsp", "unsweetened peanut butter"], [1, "pc", "ripe banana"], [1, "tbsp", "plain yogurt"]], ["Mash the banana.", "Mix with peanut butter and yogurt.", "Serve immediately or refrigerate briefly."], spreadSource, spreadNote, ["Peanut Banana Energy Spread"]),
  recipe("Egg & Cheese Spread", "snack", 200, 10, [...ATTACHED, "high-protein", "quick"], "eggs", [[2, "", "hard-boiled egg"], [1, "slice", "reduced-fat cheese"], [1, "tsp", "light mayonnaise"], [0.25, "tsp", "black pepper"]], ["Chop the eggs and cheese.", "Mix with mayonnaise and pepper.", "Chill before serving."], spreadSource, spreadNote, ["Cheese Egg Spread (Budget-Friendly)"]),
  recipe("Yogurt Fruit Spread", "snack", 150, 5, [...ATTACHED, "fruit-rich", "quick"], "yogurt", [[0.5, "cup", "plain yogurt"], [0.5, "pc", "banana"], [0.25, "cup", "apple"], [1, "tsp", "unsweetened peanut butter"]], ["Chop the fruit finely.", "Fold it into yogurt.", "Swirl in peanut butter and serve cold."], spreadSource, spreadNote, ["Yogurt Fruit Spread (Light & Fresh)"]),
];

const pairingSource = "safe healthy food combinations food nutrition health miller perez goal recipe (1).pdf";
const pairingNote = "Created from one of the healthy food combinations pictured in the attached pairing guide.";
export const PAIRING_RECIPES = [
  recipe("Rice & Beans Power Bowl", "lunch", 390, 18, [...ATTACHED, "high-fiber", "plant-protein"], "rice", [[0.5, "cup", "cooked brown rice"], [0.75, "cup", "cooked black beans"], [0.5, "cup", "tomato"], [0.25, "cup", "onion"], [1, "tbsp", "calamansi juice"], [1, "tsp", "olive oil"]], ["Warm the rice and beans.", "Top with tomato and onion.", "Finish with calamansi and olive oil."], pairingSource, pairingNote),
  recipe("Greens & Tomatoes Salad", "lunch", 210, 10, [...ATTACHED, ...EYE, "vegetable-rich"], "salad", [[2, "cup", "mixed greens"], [1, "cup", "tomato"], [0.5, "cup", "cucumber"], [1, "tbsp", "pumpkin seeds"], [2, "tsp", "olive oil"], [1, "tbsp", "lemon juice"]], ["Wash and dry the vegetables.", "Toss greens, tomato and cucumber.", "Add pumpkin seeds and dress with olive oil and lemon."], pairingSource, pairingNote),
  recipe("Egg & Cheese Breakfast Plate", "breakfast", 300, 12, [...ATTACHED, "high-protein", "portion-aware"], "eggs", [[2, "", "egg"], [1, "slice", "reduced-fat cheese"], [1, "cup", "spinach"], [0.5, "cup", "tomato"], [1, "tsp", "olive oil"]], ["Wilt spinach and tomato in olive oil.", "Cook the eggs to preference.", "Serve with one slice of cheese and the vegetables."], pairingSource, pairingNote),
  recipe("Simple Oatmeal & Water", "breakfast", 190, 8, [...ATTACHED, "whole-grain", "no-added-sugar"], "oatmeal", [[0.5, "cup", "rolled oats"], [1, "cup", "water"], [0.25, "tsp", "cinnamon"], [1, "tbsp", "ground flaxseed"]], ["Bring water to a simmer.", "Stir in oats and cook until creamy.", "Finish with cinnamon and flaxseed."], pairingSource, pairingNote),
  recipe("Tomatoes & Olive Oil Toast", "breakfast", 250, 10, [...ATTACHED, "whole-grain", "tomato-rich"], "salad", [[1, "cup", "tomato"], [1, "slice", "whole-grain bread"], [2, "tsp", "olive oil"], [1, "clove", "garlic"], [0.25, "tsp", "black pepper"]], ["Toast the bread.", "Rub with garlic and top with chopped tomato.", "Drizzle with olive oil and black pepper."], pairingSource, pairingNote),
  recipe("Berry Spinach Smoothie", "breakfast", 240, 5, [...ATTACHED, ...EYE, "fruit-rich", "leafy-greens"], "drink", [[1, "cup", "spinach"], [0.75, "cup", "mixed berries"], [0.5, "cup", "plain Greek yogurt"], [0.5, "cup", "water"], [1, "tbsp", "chia seeds"]], ["Add all ingredients to a blender.", "Blend until smooth.", "Serve immediately without added sugar."], pairingSource, pairingNote),
  recipe("Greens with Olive Oil & Garlic", "lunch", 170, 10, [...ATTACHED, ...EYE, "leafy-greens"], "salad", [[3, "cup", "leafy greens"], [2, "tsp", "olive oil"], [1, "clove", "garlic"], [1, "tbsp", "lemon juice"], [0.25, "tsp", "black pepper"]], ["Heat olive oil and garlic briefly.", "Add the greens and cook just until wilted.", "Finish with lemon and pepper."], pairingSource, pairingNote),
  recipe("Vegetable & Egg Breakfast Bowl", "breakfast", 310, 15, [...ATTACHED, ...EYE, "vegetable-rich", "high-protein"], "eggs", [[2, "", "egg"], [1, "cup", "spinach"], [0.5, "cup", "carrot"], [0.5, "cup", "red bell pepper"], [0.25, "cup", "onion"], [1, "tsp", "olive oil"]], ["Sauté the vegetables in olive oil until crisp-tender.", "Add beaten eggs and cook until just set.", "Serve in a bowl with black pepper."], pairingSource, pairingNote),
  recipe("Cayenne Chicken & Vegetables", "dinner", 420, 30, [...ATTACHED, "high-protein", "vegetable-rich"], "chickenVegetables", [[150, "g", "skinless chicken breast"], [1, "cup", "broccoli"], [0.5, "cup", "carrot"], [0.5, "cup", "bell pepper"], [0.125, "tsp", "cayenne pepper"], [2, "tsp", "olive oil"]], ["Season chicken lightly with cayenne and black pepper.", "Cook in olive oil until it reaches 74°C.", "Stir-fry the vegetables and serve alongside."], pairingSource, pairingNote),
  recipe("Oatmeal with Walnuts", "breakfast", 300, 8, [...ATTACHED, "whole-grain", "heart-healthy"], "oatmeal", [[0.5, "cup", "rolled oats"], [1, "cup", "water"], [2, "tbsp", "walnuts"], [0.25, "tsp", "cinnamon"], [0.25, "cup", "apple"]], ["Cook oats with water until creamy.", "Stir in cinnamon and chopped apple.", "Top with walnuts."], pairingSource, pairingNote),
  recipe("Egg, Bean & Pepper Breakfast Bowl", "breakfast", 360, 15, [...ATTACHED, "high-fiber", "high-protein"], "eggs", [[1, "", "egg"], [0.5, "cup", "cooked black beans"], [0.5, "cup", "red bell pepper"], [0.25, "cup", "onion"], [1, "tsp", "olive oil"], [1, "tbsp", "calamansi juice"]], ["Sauté pepper and onion in olive oil.", "Add beans and warm through.", "Top with a cooked egg and calamansi."], pairingSource, pairingNote),
  recipe("Lemon Tea Infusion", "snack", 5, 8, [...ATTACHED, "no-added-sugar", "caffeine-free"], "tea", [[1, "tsp", "herbal tea leaves"], [1, "slice", "lemon"], [1, "cup", "boiling water"], [2, "leaf", "mint"]], ["Steep the tea and mint in boiling water for five minutes.", "Strain.", "Add lemon and serve without sugar."], pairingSource, pairingNote),
  recipe("Salmon & Potato Sheet-Pan Meal", "dinner", 500, 35, [...ATTACHED, ...EYE, "omega-3", "high-protein"], "salmonSweetPotato", [[140, "g", "salmon fillet"], [1, "cup", "baby potato"], [1, "cup", "broccoli"], [2, "tsp", "olive oil"], [1, "tbsp", "lemon juice"], [0.5, "tsp", "dried dill"]], ["Roast halved potatoes with half the oil at 210°C for 15 minutes.", "Add salmon and broccoli with the remaining oil and dill.", "Roast another 12 to 14 minutes and finish with lemon."], pairingSource, pairingNote),
  recipe("Pistachio & Apple Snack", "snack", 190, 3, [...ATTACHED, "high-fiber", "quick"], "apple", [[1, "pc", "apple"], [2, "tbsp", "unsalted pistachios"]], ["Wash and slice the apple.", "Measure the pistachios.", "Serve together."], pairingSource, pairingNote),
  recipe("Dark Chocolate Almond Bites", "snack", 180, 5, [...ATTACHED, "portion-aware", "quick"], "dessert", [[15, "g", "dark chocolate"], [2, "tbsp", "unsalted almonds"], [0.125, "tsp", "cinnamon"]], ["Melt the dark chocolate gently.", "Coat the almonds and dust with cinnamon.", "Chill until set and divide into one portion."], pairingSource, pairingNote),
];

export const IMPORTED_RECIPE_DEFINITIONS = Object.freeze([
  ...EYE_SUPPORTIVE_RECIPES,
  ...COOKBOOK_RECIPES,
  ...MENU_RECIPES,
  ...PANTRY_RECIPES,
  ...SPREAD_RECIPES,
  ...PAIRING_RECIPES
]);
